---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.containers.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neondb-credentials
                  key: password
            - name: POSTGRES_HOST
              value: {{ .Values.worker.envVars.POSTGRES_HOST | quote  }}
            - name: POSTGRES_USER
              value: {{ .Values.worker.envVars.POSTGRES_USER | quote  }}
            - name: POSTGRES_DB
              value: {{ .Values.worker.envVars.POSTGRES_DB | quote  }}
            - name: KAFKA_HOST
              value: {{ .Values.worker.envVars.KAFKA_HOST | quote  }}
          ports:
            - name: worker
              containerPort: 8000
              protocol: TCP
